{% set name = "pykube" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pykube-{{ version }}.tar.gz
  sha256: e53800d0d45f13911aa4ebca8463ae5cc82afad461f6575a0a217d2fce5f088b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.12
    - requests-oauthlib
    - pyyaml
    - six >=1.10.0
    - tzlocal
    - oauth2client

test:
  imports:
    - pykube
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kelproject/pykube
  summary: Python client library for Kubernetes
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
